set(ASSET_SOURCE_DIR "${CMAKE_SOURCE_DIR}/apps/test_app/assets")

set(ASSET_DESTINATION_DIR "${CMAKE_BINARY_DIR}/bin/")


set(SETTINGS_SOURCE ${CMAKE_SOURCE_DIR}/apps/test_app/settings.ini)
set(SETTINGS_DESTINATION "${CMAKE_BINARY_DIR}/bin/")

file(COPY ${ASSET_SOURCE_DIR} DESTINATION ${ASSET_DESTINATION_DIR})
configure_file(${SETTINGS_SOURCE} ${SETTINGS_DESTINATION}/settings.ini COPYONLY)

